from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('my_fsm1', src, depend = ['PKG_USING_MY_FSM1'], CPPPATH = CPPPATH)

Return('group')
